# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

find_centroids <- function(spectrum, min_width, min_intensity) {
    .Call('_mzcharge_find_centroids', PACKAGE = 'mzcharge', spectrum, min_width, min_intensity)
}

#' Convert profile spectra to centroided spectra with assigned charge and
#' position in isotopic envelope.
#'
#' @description \code{charge_singlespec} converts single profile spectrum into
#' centroided spectrum using local maximum across \code{min_width} points.
#' Assigment of charge and isotopic position is based on mz distance between
#' isotopologues and deviation of measured intensity from predicted by
#' averagine model.
#' For high performance, \code{charge_singlespec} is implemented in C++ using
#' \href{http://www.rcpp.org}{Rcpp}.
#'
#' @param spectrum a 2-column numeric matrix with mz [,1] and intenity [,2].
#' @param min_width a size of sliding window for centroiding.
#' @param min_intensity minimal intensity for centroiding.
#' @param mz_tol max mz deviation between isotopologues (ppm).
#' @param intensity_tol max deviation between measured intensity and predicted
#' using averagine model.
#' @param max_charge max charge to assign.
#' @param num_iso max number of isotopologues to search for.
#'
#' @return A \code{data.frame}
#'
#' @export
charge_singlespec <- function(spectrum, min_width, min_intensity, mz_tol, intensity_tol, max_charge, num_iso) {
    .Call('_mzcharge_charge_singlespec', PACKAGE = 'mzcharge', spectrum, min_width, min_intensity, mz_tol, intensity_tol, max_charge, num_iso)
}

